config/routes.rb
Savontest::Application.routes.draw do
  resources :updateretes

  resources :updatehoteltexts

  resources :updatebookings

  resources :updateavails

  resources :setmarkassents

  resources :setds

  resources :getroomratecodefbs

  resources :getroomratecodes

  resources :getratesdbs

  resources :getrates

  resources :getnotificationmessages

  resources :getinvoicedata

  resources :gethotels

  resources :gethotelstaticdatagds

  resources :gethotelstaticdata

  resources :getcommissionstatuses

  resources :getbookings

  resources :getavailfbs

  resources :cancelbookings

  resources :bookings

  get "savontest/index"

end

app/models/updaterete.rb
require 'net/http'
class Updaterete <  ActiveRecord::Base
   
   

  
  def self.update_rates(params)
     uri = URI('http://test.reconline.com/recoupdate/update.asmx/UpdateRates')
  
    
  res = Net::HTTP.post_form(uri, 'User'=>params[:User],'Password'=>params[:Password],
  "idHotel"=> params[:idHotel] ,"idSystem"=>params[:idSystem],"ForeignPropCode"=>params[:ForeignPropCode],
        "IncludeRateLevels"=>params[:IncludeRateLevels],"ExcludeRateLevels"=> params[:ExcludeRateLevels],
        "IncludeRoomTypes"=>params[:IncludeRoomTypes],"ExcludeRoomTypes"=>params[:ExcludeRoomTypes],"RateType"=>
          params[:RateType],
        "StartDate"=> params[:StartDate],"EndDate"=>params[:EndDate],"SingleOcc"=>params[:SingleOcc],"DoubleOcc"=>params[:DoubleOcc],
        "TripleOcc"=>params[:TripleOcc],"DoublePlusChild"=>params[:DoublePlusChild],
        "RollawayAdult"=>params[:RollawayAdult],"RollawayChild"=>params[:RollawayChild],"Crib"=>params[:Crib],"Meals"=>params[:Meals],
        "Advance"=> params[:Advance],"MinStay"=> params[:MinStay],
        "BlockStay"=> params[:BlockStay],"Guarantee"=>params[:Guarantee],"Cancel"=>params[:Cancel],"CTAMonday"=>params[:CTAMonday],
        "CTATuesday"=>params[:CTATuesday] ,
        "CTAWednesday"=>params[:CTAWednesday],"CTAThursday"=>params[:CTAThursday],"CTAFriday"=>params[:CTAFriday],"CTASaturday"=>params[:CTASaturday],
        "CTASunday"=>params[:CTASunday],
        "InvalidMonday"=>params[:InvalidMonday],"InvalidTuesday"=>params[:InvalidTuesday],"InvalidWednesday"=>params[:InvalidWednesday],"InvalidThursday"=>params[:InvalidThursday],"InvalidFriday"=>params[:InvalidFriday],
        "InvalidSaturday"=>params[:InvalidSaturday],"InvalidSunday"=>params[:InvalidSunday])
    logger.info "the paaramsmsmsms"
    logger.info res.inspect
    logger.info res.to_hash
    logger.info res.body.include?("<boolean xmlns=\"http://www.reconline.com/\">true</boolean>")
    logger.info res.body
    logger.info res.to_hash
    res 
    
   
  end
  
  
end

app/controllers/updateretes_controller.rb
class UpdateretesController < ApplicationController
  # GET /updateretes
  # GET /updateretes.json
  def index
   # @updateretes = Updaterete.update_rates

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @updateretes }
    end
  end

  # GET /updateretes/1
  # GET /updateretes/1.json
  def show
    @updaterete = Updaterete.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @updaterete }
    end
  end

  # GET /updateretes/new
  # GET /updateretes/new.json
  def new
   # @updaterete = Updaterete.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @updaterete }
    end
  end

  # GET /updateretes/1/edit
  def edit
    @updaterete = Updaterete.find(params[:id])
  end

  # POST /updateretes
  # POST /updateretes.json
  def create
    @updaterete = Updaterete.update_rates(params)

    respond_to do |format|
      if @updaterete.save
        format.html { redirect_to @updaterete, notice: 'Updaterete was successfully created.' }
        format.json { render json: @updaterete, status: :created, location: @updaterete }
      else
        format.html { render action: "new" }
        format.json { render json: @updaterete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /updateretes/1
  # PUT /updateretes/1.json
  def update
    @updaterete = Updaterete.find(params[:id])

    respond_to do |format|
      if @updaterete.update_attributes(params[:updaterete])
        format.html { redirect_to @updaterete, notice: 'Updaterete was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @updaterete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updateretes/1
  # DELETE /updateretes/1.json
  def destroy
    @updaterete = Updaterete.find(params[:id])
    @updaterete.destroy

    respond_to do |format|
      format.html { redirect_to updateretes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/updateretes_helper.rb
module UpdateretesHelper
end

app/views/updateretes/_form.html.erb
 <form method="POST" action="/updateretes" >                      
                        
                          <table cellspacing="0" cellpadding="4" bordercolor="#dcdcdc" style="border-collapse: collapse;" rules="none" frame="box">
                          <tbody><tr>
	<td background="#dcdcdc" style="border-right: 2px solid white;" class="frmHeader">Parameter</td>
	<td background="#dcdcdc" class="frmHeader">Wert</td>
</tr>

                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">User:</td>
                            <td><input type="text" name="User" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">Password:</td>
                            <td><input type="text" name="Password" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">idHotel:</td>
                            <td><input type="text" name="idHotel" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">idSystem:</td>
                            <td><input type="text" name="idSystem" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">ForeignPropCode:</td>
                            <td><input type="text" name="ForeignPropCode" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">IncludeRateLevels:</td>
                            <td><input type="text" name="IncludeRateLevels" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">ExcludeRateLevels:</td>
                            <td><input type="text" name="ExcludeRateLevels" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">IncludeRoomTypes:</td>
                            <td><input type="text" name="IncludeRoomTypes" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">ExcludeRoomTypes:</td>
                            <td><input type="text" name="ExcludeRoomTypes" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">RateType:</td>
                            <td><input type="text" name="RateType" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">StartDate:</td>
                            <td><input type="text" name="StartDate" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">EndDate:</td>
                            <td><input type="text" name="EndDate" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">SingleOcc:</td>
                            <td><input type="text" name="SingleOcc" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">DoubleOcc:</td>
                            <td><input type="text" name="DoubleOcc" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">TripleOcc:</td>
                            <td><input type="text" name="TripleOcc" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">DoublePlusChild:</td>
                            <td><input type="text" name="DoublePlusChild" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">RollawayAdult:</td>
                            <td><input type="text" name="RollawayAdult" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">RollawayChild:</td>
                            <td><input type="text" name="RollawayChild" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">Crib:</td>
                            <td><input type="text" name="Crib" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">Meals:</td>
                            <td><input type="text" name="Meals" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">Advance:</td>
                            <td><input type="text" name="Advance" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">MinStay:</td>
                            <td><input type="text" name="MinStay" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">BlockStay:</td>
                            <td><input type="text" name="BlockStay" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">Guarantee:</td>
                            <td><input type="text" name="Guarantee" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">Cancel:</td>
                            <td><input type="text" name="Cancel" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">CTAMonday:</td>
                            <td><input type="text" name="CTAMonday" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">CTATuesday:</td>
                            <td><input type="text" name="CTATuesday" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">CTAWednesday:</td>
                            <td><input type="text" name="CTAWednesday" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">CTAThursday:</td>
                            <td><input type="text" name="CTAThursday" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">CTAFriday:</td>
                            <td><input type="text" name="CTAFriday" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">CTASaturday:</td>
                            <td><input type="text" name="CTASaturday" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">CTASunday:</td>
                            <td><input type="text" name="CTASunday" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">InvalidMonday:</td>
                            <td><input type="text" name="InvalidMonday" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">InvalidTuesday:</td>
                            <td><input type="text" name="InvalidTuesday" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">InvalidWednesday:</td>
                            <td><input type="text" name="InvalidWednesday" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">InvalidThursday:</td>
                            <td><input type="text" name="InvalidThursday" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">InvalidFriday:</td>
                            <td><input type="text" name="InvalidFriday" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">InvalidSaturday:</td>
                            <td><input type="text" name="InvalidSaturday" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">InvalidSunday:</td>
                            <td><input type="text" name="InvalidSunday" size="50" class="frmInput"></td>
                          </tr>
                        
                        <tr>
                          <td></td>
                          <td align="right"> <input type="submit" class="button" value="Aufrufen"></td>
                        </tr>
                        </tbody></table>
                      

                    </form>

app/views/updateretes/edit.html.erb
<h1>Editing updaterete</h1>

<%= render 'form' %>

<%= link_to 'Show', @updaterete %> |
<%= link_to 'Back', updateretes_path %>

app/views/updateretes/index.html.erb
<h1>Listing updateretes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

 
</table>

<br />

<%= link_to 'New Updaterete', new_updaterete_path %>

app/views/updateretes/new.html.erb
<h1>New updaterete</h1>

<%= render 'form' %>

<%= link_to 'Back', updateretes_path %>

app/views/updateretes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_updaterete_path(@updaterete) %> |
<%= link_to 'Back', updateretes_path %>