config/routes.rb
Savontest::Application.routes.draw do
  resources :updateretes

  resources :updatehoteltexts

  resources :updatebookings

  resources :updateavails

  resources :setmarkassents

  resources :setds

  resources :getroomratecodefbs

  resources :getroomratecodes

  resources :getratesdbs

  resources :getrates

  resources :getnotificationmessages

  resources :getinvoicedata

  resources :gethotels

  resources :gethotelstaticdatagds

  resources :gethotelstaticdata

  resources :getcommissionstatuses

  resources :getbookings

  resources :getavailfbs

  resources :cancelbookings

  resources :bookings

  get "savontest/index"

end

app/models/getrate.rb
require 'net/http'
class Getrate  <  ActiveRecord::Base

   

  def self.get_rates(params)
   # super("User"=>"string","Password"=>"string","idHotel"=>1,"idSystem"=>1,"ForeignPropCode"=>"string","IncludeRateLevels"=>"string",
   # "ExcludeRateLevels"=>"string","IncludeRoomTypes"=>"string","ExcludeRoomTypes"=>"string","RateType"=>"string",
  #"StartDate"=>"string","EndDate"=>"string").to_hash

    
      uri = URI('http://test.reconline.com/recoupdate/update.asmx/GetRates')
  
    
  res = Net::HTTP.post_form(uri, "User"=>params[:User],"Password"=>params[:Password],"idHotel"=>params[:idHotel],"idSystem"=>params[:idSystem],"ForeignPropCode"=>params[:ForeignPropCode],"IncludeRateLevels"=>params[:IncludeRateLevels],
    "ExcludeRateLevels"=>params[:ExcludeRateLevels],"IncludeRoomTypes"=>params[:IncludeRoomTypes],"ExcludeRoomTypes"=>params[:ExcludeRoomTypes],"RateType"=>params[:RateType],
  "StartDate"=>params[:StartDate],"EndDate"=>params[:EndDate])
    logger.info "the paaramsmsmsms"
    logger.info res.inspect
    logger.info res.to_hash
    logger.info res.body.include?("<boolean xmlns=\"http://www.reconline.com/\">true</boolean>")
    logger.info res.body
    res.to_hash
    res  
    
  end
end

app/controllers/getrates_controller.rb
class GetratesController < ApplicationController
  # GET /getrates
  # GET /getrates.json
  def index
   # getrates = Getrate.get_rates

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @getrates }
    end
  end

  # GET /getrates/1
  # GET /getrates/1.json
  def show
    @getrate = Getrate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @getrate }
    end
  end

  # GET /getrates/new
  # GET /getrates/new.json
  def new
    #@getrate = Getrate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @getrate }
    end
  end

  # GET /getrates/1/edit
  def edit
    @getrate = Getrate.find(params[:id])
  end

  # POST /getrates
  # POST /getrates.json
  def create
    getrate = Getrate.get_rates(params)

    respond_to do |format|
      if getrate.body.include?("<boolean xmlns=\"http://www.reconline.com/\">true</boolean>")
        flash[:notice] = 'Getrate was successfully created.'
        format.html { redirect_to @getrate  }
        format.json { render json: @getrate, status: :created, location: @getrate }
      else
        flash[:notice] = getrate.body
        format.html { render action: "new" }
        format.json { render json: @getrate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /getrates/1
  # PUT /getrates/1.json
  def update
    @getrate = Getrate.find(params[:id])

    respond_to do |format|
      if @getrate.update_attributes(params[:getrate])
        format.html { redirect_to @getrate, notice: 'Getrate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @getrate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /getrates/1
  # DELETE /getrates/1.json
  def destroy
    @getrate = Getrate.find(params[:id])
    @getrate.destroy

    respond_to do |format|
      format.html { redirect_to getrates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/getrates_helper.rb
module GetratesHelper
end

app/views/getrates/_form.html.erb
<form method="POST" action="/getrates" >                      
                        
                          <table cellspacing="0" cellpadding="4" bordercolor="#dcdcdc" style="border-collapse: collapse;" rules="none" frame="box">
                          <tbody><tr>
	<td background="#dcdcdc" style="border-right: 2px solid white;" class="frmHeader">Parameter</td>
	<td background="#dcdcdc" class="frmHeader">Wert</td>
</tr>

                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">User:</td>
                            <td><input type="text" name="User" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">Password:</td>
                            <td><input type="text" name="Password" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">idHotel:</td>
                            <td><input type="text" name="idHotel" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">idSystem:</td>
                            <td><input type="text" name="idSystem" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">ForeignPropCode:</td>
                            <td><input type="text" name="ForeignPropCode" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">IncludeRateLevels:</td>
                            <td><input type="text" name="IncludeRateLevels" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">ExcludeRateLevels:</td>
                            <td><input type="text" name="ExcludeRateLevels" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">IncludeRoomTypes:</td>
                            <td><input type="text" name="IncludeRoomTypes" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">ExcludeRoomTypes:</td>
                            <td><input type="text" name="ExcludeRoomTypes" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">RateType:</td>
                            <td><input type="text" name="RateType" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">StartDate:</td>
                            <td><input type="text" name="StartDate" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">EndDate:</td>
                            <td><input type="text" name="EndDate" size="50" class="frmInput"></td>
                          </tr>
                        
                        <tr>
                          <td></td>
                          <td align="right"> <input type="submit" class="button" value="Aufrufen"></td>
                        </tr>
                        </tbody></table>
                      

                    </form>

app/views/getrates/edit.html.erb
<h1>Editing getrate</h1>

<%= render 'form' %>

<%= link_to 'Show', @getrate %> |
<%= link_to 'Back', getrates_path %>

app/views/getrates/index.html.erb
<h1>Listing getrates</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

 
</table>

<br />

<%= link_to 'New Getrate', new_getrate_path %>

app/views/getrates/new.html.erb
<h1>New getrate</h1>

<%= render 'form' %>

<%= link_to 'Back', getrates_path %>

app/views/getrates/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_getrate_path(@getrate) %> |
<%= link_to 'Back', getrates_path %>