config/routes.rb
Savontest::Application.routes.draw do
  resources :updateretes

  resources :updatehoteltexts

  resources :updatebookings

  resources :updateavails

  resources :setmarkassents

  resources :setds

  resources :getroomratecodefbs

  resources :getroomratecodes

  resources :getratesdbs

  resources :getrates

  resources :getnotificationmessages

  resources :getinvoicedata

  resources :gethotels

  resources :gethotelstaticdatagds

  resources :gethotelstaticdata

  resources :getcommissionstatuses

  resources :getbookings

  resources :getavailfbs

  resources :cancelbookings

  resources :bookings

  get "savontest/index"

end

app/models/updatehoteltext.rb
require "savon_model"
class Updatehoteltext  
  
   include Savon::Model

  document "http://www.reconline.com/recoupdate/update.asmx?wsdl"
  

     actions :booking

  def booking()
    super("User"=>"string","Password"=>"string","idHotel"=>"string","idSystem"=>"string","ForeignPropCode"=>"string",
        "idType"=>"string","idlanguage"=>"string","Text"=>"string").to_hash
  end
  
end

app/controllers/updatehoteltexts_controller.rb
class UpdatehoteltextsController < ApplicationController
  # GET /updatehoteltexts
  # GET /updatehoteltexts.json
  def index
    @updatehoteltexts = Updatehoteltext.update_hotel_text

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @updatehoteltexts }
    end
  end

  # GET /updatehoteltexts/1
  # GET /updatehoteltexts/1.json
  def show
    @updatehoteltext = Updatehoteltext.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @updatehoteltext }
    end
  end

  # GET /updatehoteltexts/new
  # GET /updatehoteltexts/new.json
  def new
    @updatehoteltext = Updatehoteltext.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @updatehoteltext }
    end
  end

  # GET /updatehoteltexts/1/edit
  def edit
    @updatehoteltext = Updatehoteltext.find(params[:id])
  end

  # POST /updatehoteltexts
  # POST /updatehoteltexts.json
  def create
    @updatehoteltext = Updatehoteltext.new(params[:updatehoteltext])

    respond_to do |format|
      if @updatehoteltext.save
        format.html { redirect_to @updatehoteltext, notice: 'Updatehoteltext was successfully created.' }
        format.json { render json: @updatehoteltext, status: :created, location: @updatehoteltext }
      else
        format.html { render action: "new" }
        format.json { render json: @updatehoteltext.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /updatehoteltexts/1
  # PUT /updatehoteltexts/1.json
  def update
    @updatehoteltext = Updatehoteltext.find(params[:id])

    respond_to do |format|
      if @updatehoteltext.update_attributes(params[:updatehoteltext])
        format.html { redirect_to @updatehoteltext, notice: 'Updatehoteltext was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @updatehoteltext.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updatehoteltexts/1
  # DELETE /updatehoteltexts/1.json
  def destroy
    @updatehoteltext = Updatehoteltext.find(params[:id])
    @updatehoteltext.destroy

    respond_to do |format|
      format.html { redirect_to updatehoteltexts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/updatehoteltexts_helper.rb
module UpdatehoteltextsHelper
end

app/views/updatehoteltexts/_form.html.erb
<%= form_for(@updatehoteltext) do |f| %>
  <% if @updatehoteltext.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@updatehoteltext.errors.count, "error") %> prohibited this updatehoteltext from being saved:</h2>

      <ul>
      <% @updatehoteltext.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/updatehoteltexts/edit.html.erb
<h1>Editing updatehoteltext</h1>

<%= render 'form' %>

<%= link_to 'Show', @updatehoteltext %> |
<%= link_to 'Back', updatehoteltexts_path %>

app/views/updatehoteltexts/index.html.erb
<h1>Listing updatehoteltexts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @updatehoteltexts.each do |updatehoteltext| %>
  <tr>
    <td><%= link_to 'Show', updatehoteltext %></td>
    <td><%= link_to 'Edit', edit_updatehoteltext_path(updatehoteltext) %></td>
    <td><%= link_to 'Destroy', updatehoteltext, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Updatehoteltext', new_updatehoteltext_path %>

app/views/updatehoteltexts/new.html.erb
<h1>New updatehoteltext</h1>

<%= render 'form' %>

<%= link_to 'Back', updatehoteltexts_path %>

app/views/updatehoteltexts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_updatehoteltext_path(@updatehoteltext) %> |
<%= link_to 'Back', updatehoteltexts_path %>