config/routes.rb
Savontest::Application.routes.draw do
  resources :updateretes

  resources :updatehoteltexts

  resources :updatebookings

  resources :updateavails

  resources :setmarkassents

  resources :setds

  resources :getroomratecodefbs

  resources :getroomratecodes

  resources :getratesdbs

  resources :getrates

  resources :getnotificationmessages

  resources :getinvoicedata

  resources :gethotels

  resources :gethotelstaticdatagds

  resources :gethotelstaticdata

  resources :getcommissionstatuses

  resources :getbookings

  resources :getavailfbs

  resources :cancelbookings

  resources :bookings

  get "savontest/index"

end

app/models/getroomratecode.rb
 require 'net/http'
class Getroomratecode <  ActiveRecord::Base
 
    

  

     

  def self.get_room_rate_codes(params)
    #super("User"=>"string","Password"=>"string","idHotel"=>"string","idSystem"=>"string","ForeignPropCode"=>"string").to_hash
  
   uri = URI('http://test.reconline.com/recoupdate/update.asmx/GetRoomRateCodes')
  
    
  res = Net::HTTP.post_form(uri, "User"=>params[:User],"Password"=>params[:Password],"idHotel"=>params[:idHotel],"idSystem"=>params[:idSystem],"ForeignPropCode"=>params[:ForeignPropCode])
    logger.info "the paaramsmsmsms"
    logger.info res.inspect
    logger.info res.to_hash
    logger.info res.body.include?("<boolean xmlns=\"http://www.reconline.com/\">true</boolean>")
    logger.info res.body
    res.to_hash
    res  
  
  end
  
end

app/controllers/getroomratecodes_controller.rb
class GetroomratecodesController < ApplicationController
  # GET /getroomratecodes
  # GET /getroomratecodes.json
  def index
    #getroomratecodes = Getroomratecode.get_room_rate_codes

    #p getroomratecodes
    p "the response"
    
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @getroomratecodes }
    end
  end

  # GET /getroomratecodes/1
  # GET /getroomratecodes/1.json
  def show
    @getroomratecode = Getroomratecode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @getroomratecode }
    end
  end

  # GET /getroomratecodes/new
  # GET /getroomratecodes/new.json
  def new
     

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @getroomratecode }
    end
  end

  # GET /getroomratecodes/1/edit
  def edit
    @getroomratecode = Getroomratecode.find(params[:id])
  end

  # POST /getroomratecodes
  # POST /getroomratecodes.json
  def create
     
    @Getroomratecode = Getroomratecode.get_room_rate_codes(params)
    respond_to do |format|
      if @Getroomratecode.body.include?("<boolean xmlns=\"http://www.reconline.com/\">true</boolean>")
        flash[:notice] = 'Getroomratecode was successfully created.'
        format.html { redirect_to :action=>:index     }
        format.json { render json: @getroomratecode, status: :created, location: @getroomratecode }
      else
        flash[:notice] = @Getroomratecode.body
        format.html { render action: "new" }
        format.json { render json: @getroomratecode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /getroomratecodes/1
  # PUT /getroomratecodes/1.json
  def update
    @getroomratecode = Getroomratecode.find(params[:id])

    respond_to do |format|
      if @getroomratecode.update_attributes(params[:getroomratecode])
        format.html { redirect_to @getroomratecode, notice: 'Getroomratecode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @getroomratecode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /getroomratecodes/1
  # DELETE /getroomratecodes/1.json
  def destroy
    @getroomratecode = Getroomratecode.find(params[:id])
    @getroomratecode.destroy

    respond_to do |format|
      format.html { redirect_to getroomratecodes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/getroomratecodes_helper.rb
module GetroomratecodesHelper
end

app/views/getroomratecodes/_form.html.erb
<form method="POST" action="/getroomratecodes"  >                      
                        
                          <table cellspacing="0" cellpadding="4" bordercolor="#dcdcdc" style="border-collapse: collapse;" rules="none" frame="box">
                          <tbody><tr>
	<td background="#dcdcdc" style="border-right: 2px solid white;" class="frmHeader">Parameter</td>
	<td background="#dcdcdc" class="frmHeader">Wert</td>
</tr>

                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">User:</td>
                            <td><input type="text" name="User" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">Password:</td>
                            <td><input type="text" name="Password" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">idHotel:</td>
                            <td><input type="text" name="idHotel" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">idSystem:</td>
                            <td><input type="text" name="idSystem" size="50" class="frmInput"></td>
                          </tr>
                        
                          <tr>
                            <td style="color: #000000; font-weight: normal;" class="frmText">ForeignPropCode:</td>
                            <td><input type="text" name="ForeignPropCode" size="50" class="frmInput"></td>
                          </tr>
                        
                        <tr>
                          <td></td>
                          <td align="right"> <input type="submit" class="button" value="Aufrufen"></td>
                        </tr>
                        </tbody></table>
                      

                    </form>

app/views/getroomratecodes/edit.html.erb
<h1>Editing getroomratecode</h1>

<%= render 'form' %>

<%= link_to 'Show', @getroomratecode %> |
<%= link_to 'Back', getroomratecodes_path %>

app/views/getroomratecodes/index.html.erb
<h1>Listing getroomratecodes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

 
</table>

<br />

<%= link_to 'New Getroomratecode', new_getroomratecode_path %>

app/views/getroomratecodes/new.html.erb
<h1>New getroomratecode</h1>

<%= render 'form' %>

<%= link_to 'Back', getroomratecodes_path %>

app/views/getroomratecodes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_getroomratecode_path(@getroomratecode) %> |
<%= link_to 'Back', getroomratecodes_path %>